version: '3.8'
services:
    app: 
      build: .
      container_name: app
      ports:
        - 80:8084
      volumes:
        - .:/app
      restart: always
    db:
      image: postgres:14.1-alpine
      restart: always
      environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      ports:
      - '5432:5432'
      volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local